- modules:
  - name: [Data.Set]
    as: Set
  - name: [Data.Map, Data.Map.Strict]
    as: Map

- error: {lhs: "mapM f xs", rhs: traverse f xs}
- error: {lhs: "forM x f", rhs: for f x}
- error: {lhs: "mapM_ f x", rhs: traverse_ f x}
- error: {lhs: "forM_ x f", rhs: for_ x f}
- warning: {lhs: "mappend x y", rhs: x <> y}
