language: nix
install: true
script:
  - nix-shell . --run "cabal new-configure --enable-tests" --arg ci true
  - nix-shell . --run "cabal new-build amuletml:amc" --arg ci true
  - nix-shell . --run "cabal new-test amuletml:hedgehog-tests" --arg ci true
cache:
  directories:
  - /nix
